### ISSUE TITLE
Compilation error "macro "LINQ_WHERE" requires 3 arguments, but only 1 given"

### ISSUE THREAD

**Issue by Daiver** [pfultz2/Linq#3]
I just tried to compile hello world example and received following error 
`g++ -o main main.cpp -std=c++14 -I../Linq/
main.cpp:24:1: error: macro "LINQ_WHERE" requires 3 arguments, but only 1 given
         select(std::make_pair(student.last_name, score)));
 ^
main.cpp:24:1: error: macro "LINQ_SELECT" requires 3 arguments, but only 1 given
`

Where "main.cpp" is just copy of example from main repo page
main.cpp:
```
#include <stdio.h>
#include "linq.h"

struct student_t
{
    std::string last_name;
    std::vector<int> scores;
};

int main()
{

	std::vector<student_t> students = {
		{"Omelchenko", {97, 72, 81, 60}},
		{"O'Donnell", {75, 84, 91, 39}},
		{"Mortensen", {88, 94, 65, 85}},
		{"Garcia", {97, 89, 85, 82}},
		{"Beebe", {35, 72, 91, 70}} 
	};

	auto scores = LINQ(from(student, students) 
					   from(score, student.scores) 
					   where(score > 90) 
					   select(std::make_pair(student.last_name, score)));

	for (auto x : scores){
		printf("%s score: %i\n", x.first.c_str(), x.second);
	}

    return 0;
}

```
My compiler - gcc
gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2) 

What am I doing wrong?
PS Sorry for my poor English

**Comment by pfultz2** [comment]
The problem is boost has changed their implementation of `BOOST_PP_IS_EMPTY` and the new implementation breaks this. A simple fix is to just remove the `LINQ_SEQ_REMOVE_EMPTY` step from the `LINQ` macro, but I am not sure if this will break some other query.

**Comment by Daiver** [comment]
Thank you for answer!
Now example works fine.
Can you briefly explain purpose of LINQ_SEQ_REMOVE_EMPTY? It's a little hard for me to understand it by reading source code?

**Comment by pfultz2** [comment]
It removes empty elements from the sequence. So `(x)()(y)` becomes `(x)(y)`. I realize this is unnecessary. There won't ever be an empty element even if the user wrote `LINQ(from(x, students)())`(which is not valid anyways) because it get transformed into `(from)((x, students))(())`. Furthermore, when `LINQ_TO_SEQ` parses the string, it won't ever produce an empty element either because it stops parsing when the string becomes empty. 

So, I removed this step and pushed the change.

**Comment by Daiver** [comment]
Just cloned repo again. Looks fine.
Thank you
